#!/usr/bin/env python3

"""Hunt for sex-specific transcripts in male/female assemblies.

What are we looking for?

=> Is it full of SNPs (rather than a splice variant)?

BLAST back against male assembly

=> Is there a higher identity hit could be an X allele?
"""

import os
import fasta
from blast.blast import blast
from blast.parse import BlastResult

import logging
import logging.config
logging.config.fileConfig('logging/log.conf')
logger = logging.getLogger('root')


# Output file
i = 0
outfile = 'output.csv'
while True:
    if not os.path.exists(outfile):
        break
    outfile = 'output(%s).csv' % i
    i += 1

header = ','.join([
    'Query',
    'Subject',
    'E-value',
    'Bitscore',
    'Identities',
    'Positives',
    'Align length',
    'Q-cover percent',
])

# Sequences to use as BLAST queries
MSP_cds = fasta.read("data/sex_specific/MSP_cds.fas")
MSP_pep = fasta.read("data/sex_specific/MSP_pep.fas")
FSP_cds = fasta.read("data/sex_specific/FSP_cds.fas")
FSP_pep = fasta.read("data/sex_specific/FSP_pep.fas")

# Assemblies to BLAST against
male_hp_cds = "blast/db/hp_m_cds.fas"
female_hp_cds = "blast/db/hp_f_cds.fas"
male_hp_pep = "blast/db/hp_m_pep.fas"
female_hp_pep = "blast/db/hp_f_pep.fas"

# Generate BLAST alignments


try:
    csv = open(outfile, 'w')
    csv.write(header + '\n')

    if not result.hits:
        csv.write('%s,None,,,,,\n' % cid)
        continue

    hit = result.hits[0]
    hsp = result.hits[0].hsps[0]
    line = ','.join([
        cid,
        hit.contig_id,
        str(hsp.evalue),
        str(round(hsp.bitscore)),
        str(hsp.identities),
        str(hsp.positives),
        str(hsp.length),
        str(round(hsp.query_cover)),
    ])
    csv.write(line + '\n')
finally:
    csv.close()
